[mypy]
python_version = 3.12
disallow_untyped_defs = True
disallow_incomplete_defs = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True
warn_no_return = True
strict = True

[mypy-tests.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-alembic.*]
ignore_errors = True

[mypy-agent_framework.*]
ignore_missing_imports = True

[mypy-azure.*]
ignore_missing_imports = True
